[project]
name = "satlight"
version = "0.1.0a2"
authors = [
  { name = "L Beesley", email = "l.beesley@bham.ac.uk" },
]
description = "A package to produce high fidelity RSO lightcurves"
requires-python = ">=3.11,<3.12"
readme = "README.md"
dependencies = [
  "numpy",
  "matplotlib",
  "astropy",
  "skyfield",
  "sgp4",
  "trimesh",
  "tqdm",
  "plotly",
  "xarray",
  "netCDF4",
  "bpy==4.2.0",
  "mathutils==3.3.0",
  "hide_warnings",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["satlight*"]

[tool.setuptools.package-data]
satlight = [
  "data/ler555nm/*.dat",
  "data/ceres_albedo_monthly.npy",
]