[project]
name = "satLight"
version = "0.1x.0"
authors = [
  { name = "L Beesley", email = "l.beesley@bham.ac.uk" },
  { name = "G Jones", email = "gxj236@student.bham.ac.uk"},
]
description = "A package to produce high fidelity lightcurves"
requires-python = ">=3.9"
readme = "README.md"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
include = ["satlight"]
